### ISSUE TITLE
ApplicationContextName of non activated MAPService is received. Will send back TCAP Abort

### ISSUE THREAD

**Issue by jeenareload** [RestComm/ussdgateway#35]
Hi,

I have build USSD gateway from source after that deploy it on JBoss, then configure it with local Simulator, Stack up successfully, 
While sending PSSR request from simulator, i receive ABORT message.

10:41:57,638 WARN [MAPStackImpl-MapStack] ApplicationContextName of non activated MAPService is received. Will send back TCAP Abort : 0, 4, 0, 0, 1, 0, 19, 2,

I am attaching tshark dump.

[trace.zip](https://github.com/RestComm/ussdgateway/files/446954/trace.zip)

**Comment by vetss** [comment]
Hello @jeenareload 

1) please provide your server log
2) If you send USSD-Notify from SS7 Simulator to USSD GW then it is a wrong approach. You need to read more of a messageflow for USSD procedure. For example if you want to simulate "PULL" scenario you need to send ProcessUnstucturedUSSD message.

**Comment by jeenareload** [comment]
Hi @vetss 

a lot Thanks for your support,
I have successfully deploy ,

I have not install jain-slee properly hence facing problems, Now everything is running perfect..
