### ISSUE TITLE
Asterisk 14 and USSD Gateway

### ISSUE THREAD

**Issue by rodrigoms2004** [RestComm/ussdgateway#38]
Hi

I built a lab with my own BTS, which sends all traffic (voice, SMS and USSD) via SIP protocol. 
I would like to know how to integrate Asterisk 14 and Restcomm USSD Gateway, because Asterisk 14 has support to Sigtran (SS7 over IP).

Could  someone help me? 

Thanks in advance

**Comment by vetss** [comment]
Hello @rodrigoms2004 

USSD GW supports "Sigtran (SS7 over IP)" (this is m3ua protocol).
Which exactly problem do you have ?

**Comment by vetss** [comment]
I am closing the isse because of no response for much time.
