### ISSUE TITLE
Integrate the Restcomm Statistics

### ISSUE THREAD

**Issue by deruelle** [RestComm/ussdgateway#39]
For every USSD sent or received either through SMPP or SS7 we should ping the Restcomm statistics server at the end of the day. The integration on the USSD GW side happens through this project https://github.com/RestComm/commons/tree/master/statistics.

Ping me for more guidance

**Comment by vetss** [comment]
Fixing by:
https://github.com/RestComm/ussdgateway/commit/eed0a92afc6bf371605504802d7a1d76ffb6b7bd
https://github.com/RestComm/ussdgateway/commit/d9683e897687b8b3c7539ff9363aba81ef35b1ae
