### ISSUE TITLE
GUI management console log spelling error when updating USSD Gateway properties on Server settings

### ISSUE THREAD

**Issue by FerUy** [RestComm/ussdgateway#46]
See attached image. It should state "USSD Gateway Properties successfully updated"
![server_settings_properties_update_mgmnt_console_spelling_error](https://cloud.githubusercontent.com/assets/14883482/21668759/a2d81bde-d2e3-11e6-82b7-bb431dd751ef.png)

**Comment by vetss** [comment]
Hello @FerUy 

thanks for reporing.

**Comment by FerUy** [comment]
You're welcome @vetss 👍

**Comment by vetss** [comment]
Fixed by:

https://github.com/RestComm/ussdgateway/commit/75030fb1fb9739a2663b7c523ac373610851875d
