### ISSUE TITLE
Seperate line for interoparating with RestComm Connect

### ISSUE THREAD

**Issue by xuansinhmedia** [RestComm/ussdgateway#50]
Hi team,
I see in release note version USSD Gateway 7.x. You said fix problem:

> SIP input - replacing `&#xa;` -> `&#10;` (for interoparating with RestComm Connect server)

But when i try to test USSDGW 7 & Restcomm Connect 8.0, i seen:

```
<?xml version='1.0' encoding='UTF-8'?>
<ussd-data>
<language value="en"/>
<ussd-string value="Welcome to Telestax @&#xa;Test separate lines"/>
<anyExt>
<message-type>unstructuredSSRequest_Request</message-type>
</anyExt>
</ussd-data>]]>
</message>
```

**Comment by vetss** [comment]
Hello @xuansinhmedia 

For what do you complain ?
USSD GW 7.0 has a fix that accepts sent from Restcomm-Connect payload with  `&#xa;`, so if you see `&#xa;` in the payload it is ok. Or you mean that USSD GW does not parse it ? Please provide error in server log if any.

**Comment by xuansinhmedia** [comment]
Ok Vetss,
That is my confuse. I will try to test with real network.
