### ISSUE TITLE
Create configurable option to limit  opened dialogs for USSD GW

### ISSUE THREAD

**Issue by croufay** [RestComm/ussdgateway#55]
is there a way to better manage the queue in a way that new requests don't kill already queued dialogs. Imagine if the queue is full, new request are sent a message saying,  "please try again later"

we have it only for SMSC GW, we do not have it in USSD GW
but it looks like it is reasonable for your case to implement some threadshold
ok, let's make a configurable option for a limit of opened dialogs for USSD GW

**Comment by vetss** [comment]
Hello @croufay 

this issue is covered by https://github.com/RestComm/ussdgateway/issues/59 for a PULL case.
I am closing this issue.
