### ISSUE TITLE
Update Sip-ra.properties file to improve USSD, SIP performance

### ISSUE THREAD

**Issue by croufay** [RestComm/ussdgateway#56]
Update Sip-ra.properties file to improve USSD SIP performance with the following configuration

# Default IP address 0.0.0.0 can pickup the IP address
# automatically -- this is not a good idea if you have
# multiple interfaces.
#
# When javax.sip.IP_ADDRESS is not specified, the SIP RA
# uses the default binding address of the SLEE container
#
 
#sip stack properties that are here and in specs are obligatory for stack
gov.nist.javax.sip.AGGRESSIVE_CLEANUP=true
gov.nist.javax.sip.LOG_MESSAGE_CONTENT=false
gov.nist.javax.sip.TRACE_LEVEL=LOG4J
gov.nist.javax.sip.DEBUG_LOG=log/jsip-debuglog.txt
gov.nist.javax.sip.SERVER_LOG=log/jsip-messages.xml
gov.nist.javax.sip.LOOSE_DIALOG_VALIDATION=true
gov.nist.javax.sip.THREAD_POOL_SIZE=64
javax.sip.AUTOMATIC_DIALOG_SUPPORT=off
gov.nist.javax.sip.REENTRANT_LISTENER=true
gov.nist.javax.sip.DELIVER_UNSOLICITED_NOTIFY=true
gov.nist.javax.sip.RECEIVE_UDP_BUFFER_SIZE=131072
#gov.nist.javax.sip.RECEIVE_UDP_BUFFER_SIZE=65536
gov.nist.javax.sip.SEND_UDP_BUFFER_SIZE=131072
gov.nist.javax.sip.MAX_LISTENER_RESPONSE_TIME=120
gov.nist.javax.sip.MAX_MESSAGE_SIZE=40000
gov.nist.javax.sip.MESSAGE_PROCESSOR_FACTORY=gov.nist.javax.sip.stack.NioMessageProcessorFactory

**Comment by vetss** [comment]
Hello @croufay 

where do we have these properties ? Are there in SIP RA jar or they are in some other place ?
Are these setting specific for USSD GW or that are recommended settings for othe productls like SMSC GW too ?

**Comment by deruelle** [comment]
Closing that one. It's being done in SLEE instead in the product
