### ISSUE TITLE
Update default run.conf java OPTS for production support

### ISSUE THREAD

**Issue by croufay** [RestComm/ussdgateway#57]
the java OPTS in run.conf should be updated to use the following options for production. This should be default and for testing it can be reduced to accomodate the test environment

 Specify options to pass to the Java VM.
#
if [ "x$JAVA_OPTS" = "x" ]; then
   JAVA_OPTS="-Xms8g -Xmx8g -Xmn512m -XX:+CMSIncrementalPacing -XX:CMSIncrementalDutyCycle=100 -XX:CMSIncrementalDutyCycleMin=100 -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:MaxPermSize=512m -Djava.net.preferIPv4Stack=true -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/telestax/jvm-dump/"
fi

**Comment by vetss** [comment]
I think this option must be done at SLEE binaries level so it will be available for all products.

**Comment by deruelle** [comment]
Yes done in Telscale already
