### ISSUE TITLE
Update eventRouterThreads update to 64 from the previous value of 8

### ISSUE THREAD

**Issue by croufay** [RestComm/ussdgateway#58]
evenRouterThreads update to 64 from the previous value of 8
        <annotation>@org.jboss.aop.microcontainer.aspects.jmx.JMX(name="org.mobicents.slee:name=EventRouterConfiguration",exposedInterface=org.mobicents.slee.container.management.jmx.EventRouterConfigurationMBean.class,registerDirectly=true)</annotation>
        <property name="eventRouterThreads">64</property>
        <property name="collectStats">true</property>
        <property name="confirmSbbEntityAttachement">true</property>        
        <property name="executorMapperClassName">org.mobicents.slee.runtime.eventrouter.mapping.ActivityHashingEventRouterExecutorMapper</property>

**Comment by vetss** [comment]
I think this option must be done at SLEE binaries level so it will be available for all products.

**Comment by deruelle** [comment]
Yes done in telscale already
