### ISSUE TITLE
Wrong URL in the documentation

### ISSUE THREAD

**Issue by greg-sikora** [RestComm/ussdgateway#60]
Please can you check the documentation and correct the to the right ULR

In secion:
http://documentation.telestax.com/core/ussd/USSD_Gateway_Admin_Guide.html#_http_messages_ussd_push

> 7.2. HTTP Message Structure - USSD Push
> For USSD PUSH, the third party application should send a HTTP POST request to the Restcomm USSD GateWay . The URL for sending this is **http://<bind address of JBoss>:8080/mobicents**. The diagram below depicts an example message sequence (USSD Push) for interacting with the Restcomm USSD GateWay HTTP API

https://github.com/RestComm/ussdgateway/blob/master/docs/adminguide/sources-asciidoc/src/main/asciidoc/Chapter-HTTP_Architecture.adoc#2-http-message-structure---ussd-push

As far as I know it should be http://localhost:8080/restcomm

/Greg

**Comment by vetss** [comment]
Fixed by:

https://github.com/RestComm/ussdgateway/commit/ecbf3244fd9bf922688a8a016beb79b3c58b36b1
