### ISSUE TITLE
[NOT A BUG] [Simulator Profile] ipChannelType default to 1 instead of 0 in  SCTP management file (SCTPManagement_sctp.xml) in the binary release.

### ISSUE THREAD

**Issue by ElvisAttro** [RestComm/ussdgateway#66]
I'm only starting to get my head on the gateway, but for what i've seen, it seems like SCTP is the recommended channel type (over IP mostly on windows and even not recommended for production there). 
The absence of this information leads to an error while trying to connect to the gateway on simulator mode with the JSS7 simulator tool, causing the following output: 

`100950 [Thread-1] ERROR org.mobicents.protocols.sctp.SelectorThread  - Exception while finishing connection for Association=Ass_main
java.net.ConnectException: Connection refused
	at sun.nio.ch.SctpChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SctpChannelImpl.finishConnect(SctpChannelImpl.java:475)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnectionSctp(SelectorThread.java:381)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnection(SelectorThread.java:366)
	at org.mobicents.protocols.sctp.SelectorThread.run(SelectorThread.java:151)
	at java.lang.Thread.run(Thread.java:745)
`

Of course, this is not a bug and more of a config issue, that is easily resolved by manually setting ipChannelType to 0 in SCTPManagement_sctp.xml, but i think default the value to 0 may be a huge time saver for those who are trying the gateway for the first time.
This will also make the testing process stay consistent with the official documentation, as there is no mention there to set the ipChannelType prior testing the gateway in simulator profile. 

Please, feel free to correct me if i'm wrong.
thank you.

**Comment by vetss** [comment]
Hello @ElvisAttro 

thanks for your update. This bug was already fixed by commit:
https://github.com/RestComm/ussdgateway/commit/fa315557dc041d2cd5049a8fb0cbc13de0a0b300

But we has not made a new USSD GW release sinse that. So I can advise only to fix the problem locally.

**Comment by ElvisAttro** [comment]
Got it! 
Thank you.
