### ISSUE TITLE
Is RestComm ussdgateway compatible with China UAP?

### ISSUE THREAD

**Issue by ifiok** [RestComm/ussdgateway#84]
Does this gateway support managing ussd sessions with gateways over Huawei China UAP protocol?

**Comment by gsaslis** [comment]
Hi @ifiok ! 

thanks for raising this. Would you mind sharing some more details about the protocol in question, so we can look into it in more detail?

**Comment by ElvisAttro** [comment]
Hi @ifiok @gsaslis  you may check https://github.com/RestComm/ussdgateway/issues/71 as a starter.

**Comment by gsaslis** [comment]
Thanks @ElvisAttro . 

@ifiok i'm closing this as duplicate. Please track progress in #71 and help share feedback there , otherwise please feel free to reopen this if you had a different question.
